### PR TITLE
2-1 puzzle fix

### PR DESCRIPTION
**Pull request by PDiddyDong**

### CODE REVIEW

**Comment by NPTP** [comment]
[2-1 Puzzle fix](https://trello.com/c/TtU30bcg/254-2-1-puzzle-fix)

**Comment by tylerweston** [comment]
I like it, plus it cuts out the skip so you have to do the puzzle. :shipit:

**Comment by NPTP** [comment]
I keep getting crate misalignments and can't finish the new puzzle, after several tries taking different crate paths (see img below)
I also got the bug where the crate in the new puzzle moves a tile of the level. Might make this a good testing ground to try to isolate the bug.

image

**Comment by NPTP** [comment]
Fixed!

**Pull request merged**
