### PR TITLE
DOTween, dialog system, beginnings of state manager

### PR DESCRIPTION
**Pull request by NPTP**
- Added DOTween library, just saves a lot of time for UI animations vs. the Unity animator. Simply ignore it if you don't want to use it, it has a small footprint and doesn't mess with anything else.
- Started a new state manager to control player state. Changed a few things already like movement during dialogs, disallowing spam of char switch, etc.
    - Use GetState() and SetState() to change states. States are defined in an enum in StateManager.
    - Use GetSelected() and SetSelected() for which char is selected. The getter returns the GameObject, setter takes one.
- Dialog system is up and running. Not attached to any other game logic yet, but will be easy to engage. There is a Dialog class which is basically just a struct for the headers, subtitles and paragraph strings of text, and you call dialogManager.NewDialog(Dialog) to get things rolling. It handles switching state, so it'll take care of itself.
- Made prefabs of DialogBox (meant for the Canvas), StateManager and DialogManager (latter 2 are just empty objects with script slapped on)

## To test, go to scene Scenes/TestScenes/DialogSystemTest/DialogSystemTest.unity. Simply play for 3 seconds and a dialog will pop up, with prompts.

### CODE REVIEW

**Comment by tylerweston** [comment]
Looks good to me!
Look at you and your fancy null conditional operator in there! I've been trying to sneak a  null coalescing operator in somewhere but I haven't found a place yet!

One thing, how will adding new dialogue work? It is hard coded into the individual levels DialogueManager? Might be better to read dialogue from a txt file or something?

**Review by tylerweston — APPROVED** [review]
:shipit: 
:shipit: 
:shipit:

**Comment by tylerweston** [comment]
edit ya know, I'm going to merge this anyways since I'm going to use it for pause screen, and I'll just move the discussion to the discord

**Comment by NPTP** [comment]
> One thing, how will adding new dialogue work? It is hard coded into the individual levels DialogueManager? Might be better to read dialogue from a txt file or something?

No hardcoding into the dialog manager. We can put it right into the tape pickup on that level (using public string fields we can type into), or a scriptable object stores the text for every tape in the whole game and we get it from there, or we could indeed read it from a text file!

**Pull request merged**
