### PR TITLE
Interact symbols

### PR DESCRIPTION
**Pull request by NPTP**
NOTE: Will require a touch-up run through, maybe an additional script for keycards + tapes if we want em.

Icon that shows if a switch is player- or robot-operable, now part of trigger effects. Demands that the trigger actually connects to the trigger effects (as it was always meant to, but some aren't attached, thus the need for a runthrough). Also, setting colors in the runthrough will be important, since getting the color from the trigger fx light doesn't look correct.

### CODE REVIEW

**Comment by NPTP** [comment]
[Symbol (or other indicator) on robot-only switches to indicate their robot-only-ness, same for player-only switches (and for keycards etc!)](https://trello.com/c/NlBRyUdk/246-symbol-or-other-indicator-on-robot-only-switches-to-indicate-their-robot-only-ness-same-for-player-only-switches-and-for-keycard)

**Comment by tylerweston** [comment]
image
not sure if this is supposed to be like this but there is a giant icon just kinda floating here?

**Comment by NPTP** [comment]
> not sure if this is supposed to be like this but there is a giant icon just kinda floating here?

Yeah we gotta fix that stuff in a runthrough

**Comment by NPTP** [comment]
Flipping icons at halfway point of grav flip has been implemented! Give it a look, ready to merge at your convenience!

**Comment by tylerweston** [comment]
should the icons be lined up so they are parallel to the camera? otherwise at some times it's rather hard to see what they are supposed to be?
image

**Pull request merged**
